name: Java CI/CD with Maven, JSP and JUnit # Nome do Workflow

on:  # Definindo os eventos de disparo
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:  # Chamando a tarefa de 'build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

      - name: Run JUnit Tests
        run: mvn -B test --file pom.xml
